#!/bin/bash

################################################################################
# Output generated by Eclipse.
################################################################################
# make all
# Building file: ../system/src/newlib/_cxx.cpp
# Invoking: GNU ARM Cross C++ Compiler
# arm-none-eabi-g++ -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu++11 -fabi-version=0 -MMD -MP -MF"system/src/newlib/_cxx.d" -MT"system/src/newlib/_cxx.o" -c -o "system/src/newlib/_cxx.o" "../system/src/newlib/_cxx.cpp"
# Finished building: ../system/src/newlib/_cxx.cpp

# Building file: ../system/src/newlib/_exit.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/newlib/_exit.d" -MT"system/src/newlib/_exit.o" -c -o "system/src/newlib/_exit.o" "../system/src/newlib/_exit.c"
# Finished building: ../system/src/newlib/_exit.c

# Building file: ../system/src/newlib/_sbrk.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/newlib/_sbrk.d" -MT"system/src/newlib/_sbrk.o" -c -o "system/src/newlib/_sbrk.o" "../system/src/newlib/_sbrk.c"
# Finished building: ../system/src/newlib/_sbrk.c

# Building file: ../system/src/newlib/_startup.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/newlib/_startup.d" -MT"system/src/newlib/_startup.o" -c -o "system/src/newlib/_startup.o" "../system/src/newlib/_startup.c"
# Finished building: ../system/src/newlib/_startup.c

# Building file: ../system/src/newlib/_syscalls.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/newlib/_syscalls.d" -MT"system/src/newlib/_syscalls.o" -c -o "system/src/newlib/_syscalls.o" "../system/src/newlib/_syscalls.c"
# Finished building: ../system/src/newlib/_syscalls.c

# Building file: ../system/src/newlib/assert.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/newlib/assert.d" -MT"system/src/newlib/assert.o" -c -o "system/src/newlib/assert.o" "../system/src/newlib/assert.c"
# Finished building: ../system/src/newlib/assert.c

# Building file: ../system/src/diag/Trace.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/diag/Trace.d" -MT"system/src/diag/Trace.o" -c -o "system/src/diag/Trace.o" "../system/src/diag/Trace.c"
# Finished building: ../system/src/diag/Trace.c

# Building file: ../system/src/diag/trace_impl.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/diag/trace_impl.d" -MT"system/src/diag/trace_impl.o" -c -o "system/src/diag/trace_impl.o" "../system/src/diag/trace_impl.c"
# Finished building: ../system/src/diag/trace_impl.c

# Building file: ../system/src/cortexm/_initialize_hardware.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/cortexm/_initialize_hardware.d" -MT"system/src/cortexm/_initialize_hardware.o" -c -o "system/src/cortexm/_initialize_hardware.o" "../system/src/cortexm/_initialize_hardware.c"
# Finished building: ../system/src/cortexm/_initialize_hardware.c

# Building file: ../system/src/cortexm/_reset_hardware.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/cortexm/_reset_hardware.d" -MT"system/src/cortexm/_reset_hardware.o" -c -o "system/src/cortexm/_reset_hardware.o" "../system/src/cortexm/_reset_hardware.c"
# Finished building: ../system/src/cortexm/_reset_hardware.c

# Building file: ../system/src/cortexm/exception_handlers.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/cortexm/exception_handlers.d" -MT"system/src/cortexm/exception_handlers.o" -c -o "system/src/cortexm/exception_handlers.o" "../system/src/cortexm/exception_handlers.c"
# Finished building: ../system/src/cortexm/exception_handlers.c

# Building file: ../system/src/cmsis/system_DEVICE.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/cmsis/system_DEVICE.d" -MT"system/src/cmsis/system_DEVICE.o" -c -o "system/src/cmsis/system_DEVICE.o" "../system/src/cmsis/system_DEVICE.c"
# Finished building: ../system/src/cmsis/system_DEVICE.c

# Building file: ../system/src/cmsis/vectors_DEVICE.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"system/src/cmsis/vectors_DEVICE.d" -MT"system/src/cmsis/vectors_DEVICE.o" -c -o "system/src/cmsis/vectors_DEVICE.o" "../system/src/cmsis/vectors_DEVICE.c"
# Finished building: ../system/src/cmsis/vectors_DEVICE.c

# Building file: ../src/Timer.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"src/Timer.d" -MT"src/Timer.o" -c -o "src/Timer.o" "../src/Timer.c"
# Finished building: ../src/Timer.c

# Building file: ../src/_write.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"src/_write.d" -MT"src/_write.o" -c -o "src/_write.o" "../src/_write.c"
# Finished building: ../src/_write.c

# Building file: ../src/main.c
# Invoking: GNU ARM Cross C Compiler
# arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -DDEBUG -DTRACE -DOS_USE_TRACE_SEMIHOSTING_DEBUG -I"../include" -I"../system/include" -I"../system/include/cmsis" -I"../system/include/DEVICE" -std=gnu11 -MMD -MP -MF"src/main.d" -MT"src/main.o" -c -o "src/main.o" "../src/main.c"
# Finished building: ../src/main.c

# Building target: blinkingled_cortexm0_6.elf
# Invoking: GNU ARM Cross C++ Linker
# arm-none-eabi-g++ -mcpu=cortex-m0 -mthumb -Og -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -ffreestanding -fno-move-loop-invariants -Wall -Wextra  -g3 -T mem.ld -T libs.ld -T sections.ld -nostartfiles -Xlinker --gc-sections -L"../ldscripts" -Wl,-Map,"blinkingled_cortexm0_6.map" --specs=nano.specs -o "blinkingled_cortexm0_6.elf"  ./system/src/newlib/_cxx.o ./system/src/newlib/_exit.o ./system/src/newlib/_sbrk.o ./system/src/newlib/_startup.o ./system/src/newlib/_syscalls.o ./system/src/newlib/assert.o  ./system/src/diag/Trace.o ./system/src/diag/trace_impl.o  ./system/src/cortexm/_initialize_hardware.o ./system/src/cortexm/_reset_hardware.o ./system/src/cortexm/exception_handlers.o  ./system/src/cmsis/system_DEVICE.o ./system/src/cmsis/vectors_DEVICE.o  ./src/Timer.o ./src/_write.o ./src/main.o
# Finished building target: blinkingled_cortexm0_6.elf

# Invoking: GNU ARM Cross Create Flash Image
# arm-none-eabi-objcopy -O ihex "blinkingled_cortexm0_6.elf"  "blinkingled_cortexm0_6.hex"
# Finished building: blinkingled_cortexm0_6.hex

# Invoking: GNU ARM Cross Print Size
# arm-none-eabi-size --format=berkeley "blinkingled_cortexm0_6.elf"
#    text	   data	    bss	    dec	    hex	filename
#    3553	    160	    416	   4129	   1021	blinkingled_cortexm0_6.elf
# Finished building: blinkingled_cortexm0_6.siz
################################################################################

# Compiling just the main function
# /home/vfinotti/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc \
#     -mcpu=cortex-m0 \
#     -mthumb \
#     -Og \
#     -fmessage-length=0 \
#     # -fsigned-char \
#     # -ffunction-sections \
#     # -fdata-sections \
#     # -ffreestanding \
#     # -fno-move-loop-invariants \
#     # -Wall \
#     # -Wextra  \
#     # -g3 \
#     # -DDEBUG \
#     # -DTRACE \
#     # -DOS_USE_TRACE_SEMIHOSTING_DEBUG \
#     # -I"../include" \
#     # -I"../system/include" \
#     # -I"../system/include/cmsis" \
#     # -I"../system/include/DEVICE" \
#     # -std=gnu11 \
#     # -MMD \
#     # -MP \
#     # -MF"src/main.d" \
#     # -MT"src/main.o" \
#     # -c \
#     -o "src/main.o" \
#     "../src/main.c"

# Linking
# arm-none-eabi-g++ \
#     # -mcpu=cortex-m0 \
#     # -mthumb \
#     # -Og \
#     # -fmessage-length=0 \
#     # -fsigned-char \
#     # -ffunction-sections \
#     # -fdata-sections \
#     # -ffreestanding \
#     # -fno-move-loop-invariants \
#     # -Wall \
#     # -Wextra \
#     # -g3 \
#     -T mem.ld \ # *
#     -T libs.ld \ # *
#     -T sections.ld \ # *
#     -nostartfiles \ # *
#     -Xlinker \ # *
#     --gc-sections \ # *
#     -L"../ldscripts" \ # *
#     -Wl,-Map,"blinkingled_cortexm0_6.map" \ # *
#     --specs=nano.specs \ # *
#     -o "blinkingled_cortexm0_6.elf" \ # *
#     ./system/src/newlib/_cxx.o ./system/src/newlib/_exit.o ./system/src/newlib/_sbrk.o ./system/src/newlib/_startup.o ./system/src/newlib/_syscalls.o ./system/src/newlib/assert.o  ./system/src/diag/Trace.o ./system/src/diag/trace_impl.o  ./system/src/cortexm/_initialize_hardware.o ./system/src/cortexm/_reset_hardware.o ./system/src/cortexm/exception_handlers.o  ./system/src/cmsis/system_DEVICE.o ./system/src/cmsis/vectors_DEVICE.o  ./src/Timer.o ./src/_write.o ./src/main.o

# Nice info on https://www3.ntu.edu.sg/home/ehchua/programming/cpp/gcc_make.html#zz-1.7

# Preprocessing (includes headers and expand macros)
/home/vfinotti/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-cpp \
    -mcpu=cortex-m0 \
    -mthumb \
    -g \
    --specs=rdimon.specs\
    -lc \
    -lrdimon \
    -o blinking_led.i \
    ./blinking_led.c

# Compilation (Compiles pre-processed code into assembly code for a specific
# processor)
/home/vfinotti/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-gcc \
    -mcpu=cortex-m0 \
    -mthumb \
    -g \
    --specs=rdimon.specs\
    -lc \
    -lrdimon \
    -S \
    ./blinking_led.i

# Assembly (Converts the assembly code into machine code in an object file)
/home/vfinotti/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-as \
    -mcpu=cortex-m0 \
    -mthumb \
    -g \
    -o blinking_led.o \
    ./blinking_led.s

# Linking (Links several object files and libraries)
/home/vfinotti/gcc-arm-none-eabi-7-2018-q2-update/bin/arm-none-eabi-ld \
    -o blinking_led.out \
    ./blinking_led.o
